// Arquivo gerado para converter tokens em seus nomes
package luanova

// TokenName retorna o nome do token a partir do seu código
func TokenName(tok int) string {
	switch tok {
	case Illegal:
		return "Illegal"
	case EOF:
		return "EOF"
	case Comment:
		return "Comment"
	case CommentBlock:
		return "CommentBlock"
	case True:
		return "True"
	case False:
		return "False"
	case Literal:
		return "Literal"
	case Function:
		return "Function"
	case Local:
		return "Local"
	case If:
		return "If"
	case ElseIf:
		return "ElseIf"
	case Else:
		return "Else"
	case While:
		return "While"
	case For:
		return "For"
	case End:
		return "End"
	case Then:
		return "Then"
	case Repeat:
		return "Repeat"
	case Continue:
		return "Continue"
	case Break:
		return "Break"
	case In:
		return "In"
	case Return:
		return "Return"
	case Do:
		return "Do"
	case Not:
		return "Not"
	case NotEqual:
		return "NotEqual"
	case Or:
		return "Or"
	case Greater:
		return "Greater"
	case Less:
		return "Less"
	case GreaterEqual:
		return "GreaterEqual"
	case LessEqual:
		return "LessEqual"
	case And:
		return "And"
	case Assign:
		return "Assign"
	case Equal:
		return "Equal"
	case PlusAssign:
		return "PlusAssign"
	case SubAssign:
		return "SubAssign"
	case MultiAssign:
		return "MultiAssign"
	case DivAssign:
		return "DivAssign"
	case ModAssign:
		return "ModAssign"
	case Declaration:
		return "Declaration"
	case Plus:
		return "Plus"
	case Sub:
		return "Sub"
	case Multi:
		return "Multi"
	case Div:
		return "Div"
	case Mod:
		return "Mod"
	case Po:
		return "Po"
	case Concat:
		return "Concat"
	case StringDelim:
		return "StringDelim"
	case LParen:
		return "LParen"
	case RParen:
		return "RParen"
	case LBrace:
		return "LBrace"
	case RBrace:
		return "RBrace"
	case LBrack:
		return "LBrack"
	case RBrack:
		return "RBrack"
	case Comma:
		return "Comma"
	case Semi:
		return "Semi"
	case Colom:
		return "Colom"
	case Dot:
		return "Dot"
	case Dots:
		return "Dots"
	case Arrow:
		return "Arrow"
	case Question:
		return "Question"
	case String:
		return "String"
	case Int:
		return "Int"
	case Bool:
		return "Bool"
	case Float:
		return "Float"
	default:
		return "Unknown"
	}
}
